"""Generate the agent and provider reference straight from the code.

    python -m app.tools.gen_docs

Documentation that is written by hand next to code drifts from it. The agent
table in ``docs/agents.md`` and the source table in ``docs/providers.md`` are
generated from the class declarations, so if an agent's responsibility changes
and the doc is not regenerated, ``test_docs.py`` fails.
"""

from __future__ import annotations

import os
import sys

from app.agents.planner.routing import ROUTES, skipped_for
from app.config.settings import get_settings
from app.services.container import AGENT_CLASSES, Container

BANNER = "<!-- GENERATED by `python -m app.tools.gen_docs`. Do not edit by hand. -->"


def agents_markdown() -> str:
    lines = [BANNER, "", "# Agents", "",
             "Every ORCA agent declares its responsibility, its typed inputs and",
             "outputs, the sources it may consult, and what it does when those fail.",
             "This table is generated from those declarations.", ""]
    lines += ["| Agent | Capability | Optional | Responsibility |",
              "|---|---|---|---|"]
    for cls in AGENT_CLASSES:
        d = cls.describe()
        lines.append(f"| `{d['name']}` | `{d['capability']}` | "
                     f"{'yes' if d['optional'] else 'no'} | {d['responsibility']} |")
    lines += ["", "## Detail", ""]
    for cls in AGENT_CLASSES:
        d = cls.describe()
        lines += [f"### `{d['name']}`", "",
                  f"- **Capability**: `{d['capability']}`",
                  f"- **Responsibility**: {d['responsibility']}",
                  f"- **Consumes**: {', '.join(d['consumes']) or '-'}",
                  f"- **Produces**: {', '.join(d['produces']) or '-'}",
                  f"- **Sources**: {', '.join(d['sources']) or '-'}",
                  f"- **Optional**: {'yes' if d['optional'] else 'no'}",
                  f"- **On failure**: {d['failure_behaviour']}", ""]
    lines += ["## Routing", "",
              "The planner selects capabilities by intent. Steps with no dependency",
              "edge between them execute concurrently.", ""]
    for intent, steps in ROUTES.items():
        lines.append(f"### `{intent.value}`")
        lines.append("")
        lines.append("| Capability | Required | Depends on | Why |")
        lines.append("|---|---|---|---|")
        for step in steps:
            deps = ", ".join(f"`{d.value}`" for d in step.depends_on) or "-"
            lines.append(f"| `{step.capability.value}` | "
                         f"{'yes' if step.required else 'no'} | {deps} | {step.reason} |")
        skipped = skipped_for(intent)
        if skipped:
            lines.append("")
            lines.append("Not invoked, and why:")
            lines.append("")
            for capability, reason in skipped.items():
                lines.append(f"- `{capability}` - {reason}")
        lines.append("")
    return "\n".join(lines)


def providers_markdown() -> str:
    container = Container.build(get_settings())
    lines = [BANNER, "", "# Data sources", "",
             "Generated from the provider registry. `verified_access` means the",
             "access mechanism has been checked against the operator's own",
             "documentation; it does **not** mean this deployment can reach it.", ""]
    lines += ["| Provider | Source | Origin | Verified | Role |", "|---|---|---|---|---|"]
    for p in container.registry.describe_all():
        lines.append(f"| `{p['provider_id']}` | {p['source']} | {p['origin']} | "
                     f"{'yes' if p['verified_access'] else 'no'} | {p['role']} |")
    lines += ["", "## Detail", ""]
    for p in container.registry.describe_all():
        lines += [f"### `{p['provider_id']}`", "",
                  f"- **Source family**: {p['source']}",
                  f"- **Data origin**: {p['origin']}",
                  f"- **Role**: {p['role']}",
                  f"- **Access mechanism**: {p['access_mechanism']}",
                  f"- **Attribution**: {p['attribution']}",
                  f"- **Verified access**: {'yes' if p['verified_access'] else 'no'}"]
        if p.get("verification_note"):
            lines.append(f"- **Verification note**: {p['verification_note']}")
        if p.get("variables"):
            lines.append(f"- **Canonical variables**: "
                         + ", ".join(f"`{v}`" for v in p["variables"]))
        if p.get("update_frequency_seconds"):
            lines.append(f"- **Update cycle**: {p['update_frequency_seconds']} s; "
                         f"acceptable age {p['max_acceptable_age_seconds']} s")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    root = os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))), "..", "docs")
    root = os.path.normpath(root)
    os.makedirs(root, exist_ok=True)
    for name, text in (("agents.md", agents_markdown()),
                       ("providers-generated.md", providers_markdown())):
        path = os.path.join(root, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text + "\n")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
